// Admin backend smoke test. Needs a LOCAL Mongo holding a migrated copy of the
// data (see the candidate backend: seedQuestions.js + migrateSubmissions.js).
//   SMOKE_MONGO=mongodb://127.0.0.1:27099/mfc_migrate node scripts/smoke.mjs
process.env.CONNECT_STRING = process.env.SMOKE_MONGO || "mongodb://127.0.0.1:27099/mfc_migrate";
if (!/127\.0\.0\.1|localhost/.test(process.env.CONNECT_STRING)) throw new Error("smoke test only runs against a local Mongo");
process.env.ACCESS_TOKEN_SECERT = "smoke-secret";
process.env.VERCEL = "1"; // don't listen, we mount the app ourselves
const root = new URL("..", import.meta.url).pathname.replace(/\/$/, "");
const { default: app } = await import(root + "/backend/server.js");
const mongoose = (await import(root + "/node_modules/mongoose/index.js")).default;
const bcrypt = (await import(root + "/node_modules/bcrypt/bcrypt.js")).default;
const server = app.listen(5098);
const U = "http://127.0.0.1:5098";
let fails = 0;
const expect = (n, c, x) => { console.log(`${c ? "PASS" : "FAIL"}  ${n}`, c ? "" : JSON.stringify(x)?.slice(0, 300)); if (!c) fails++; };
const call = async (m, p, { token, body } = {}) => { const r = await fetch(U + p, { method: m, headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: body ? JSON.stringify(body) : undefined }); let d = null; try { d = await r.json(); } catch {} return { status: r.status, data: d }; };
await call("GET", "/health");
const Users = mongoose.connection.db.collection("users");
await Users.deleteMany({ email: { $in: ["admin@smoke.in", "cand@smoke.in"] } });
await Users.insertOne({ username: "Smoke Admin", email: "admin@smoke.in", regno: "ADMSMOKE", password: await bcrypt.hash("pw", 4), admin: true, verified: true, tech: 0, design: 0, management: 0, isCore: false, isProfileDone: true });
await Users.insertOne({ username: "Smoke Cand", email: "cand@smoke.in", regno: "CANDSMOKE", password: await bcrypt.hash("pw", 4), admin: false, verified: true, tech: 0, design: 0, management: 0, isCore: false, isProfileDone: true });
let r = await call("POST", "/auth/login", { body: { email: "cand@smoke.in", password: "pw" } });
expect("non-admin cannot log in", r.status === 401 && r.data.message === "Invalid credentials", r);
r = await call("POST", "/auth/login", { body: { email: "nobody@smoke.in", password: "pw" } });
expect("unknown email gives same error", r.status === 401 && r.data.message === "Invalid credentials", r);
r = await call("POST", "/auth/login", { body: { email: "admin@smoke.in", password: "pw" } });
expect("admin login", r.status === 200 && r.data.accessToken, r);
const tok = r.data.accessToken;
r = await call("GET", "/admin/users/x");
expect("users needs auth", r.status === 401);
r = await call("GET", "/admin/users/x", { token: tok });
const withTasks = r.data.data.filter((u) => u.techTasks.length || u.designTasks.length || u.managementTasks.length);
expect("lists candidates with submissions", r.status === 200 && withTasks.length > 0, { n: withTasks.length });
expect("no password hashes leak", r.data.data.every((u) => !u.password && !u.refreshToken));
expect("admins excluded from list", !r.data.data.some((u) => u.admin));
const sample = withTasks.find((u) => u.managementTasks[0]?.isDone);
expect("answers are keyed objects", sample && Object.keys(sample.managementTasks[0].answers).every((k) => k.startsWith("management-")), sample?.managementTasks[0]);
r = await call("GET", "/admin/usersmanagement/x", { token: tok });
expect("domain list filters", r.data.data.every((u) => u.domain.includes("management")));
r = await call("GET", "/admin/subdomain-status", { token: tok });
expect("subdomain status", r.status === 200 && Object.keys(r.data.management).length > 0, r.data);
r = await call("PUT", "/admin/updatestatus/update", { token: tok, body: { regno: "CANDSMOKE", tech: 1, note: "good" } });
expect("status update logs event", r.status === 200 && r.data.events.length === 1 && r.data.events[0].actor === "admin@smoke.in", r.data);
r = await call("PUT", "/admin/updatestatus/update", { token: tok, body: { regno: "CANDSMOKE", tech: 9 } });
expect("bad round rejected", r.status === 400);
const cand = await Users.findOne({ email: "cand@smoke.in" });
r = await call("GET", `/admin/history/${cand._id}`, { token: tok });
expect("history returns events", r.data.data.length === 1 && r.data.data[0].to === 1, r.data);
r = await call("GET", "/admin/questions", { token: tok });
expect("questions include rubric field and inactive ones", r.data.data.length === 64 && "rubric" in r.data.data[0], r.data.data.length);
r = await call("PATCH", "/admin/questions/tech-ml-1", { token: tok, body: { rubric: "Mentions labelled vs unlabelled data", prompt: "hacked" } });
expect("rubric editable, prompt not", r.data.data.rubric.startsWith("Mentions") && r.data.data.prompt !== "hacked", r.data);
await Users.updateOne({ email: "admin@smoke.in" }, { $set: { admin: false } });
r = await call("GET", "/admin/users/x", { token: tok });
expect("revoked admin locked out immediately", r.status === 403, r.status);
await Users.deleteMany({ email: { $in: ["admin@smoke.in", "cand@smoke.in"] } });
await mongoose.connection.db.collection("statusevents").deleteMany({ user_id: cand._id });
console.log(fails ? `${fails} FAILED` : "ALL PASS");
server.close(); await mongoose.disconnect(); process.exit(fails ? 1 : 0);
